### ISSUE TITLE
Trigger automations via MQTT messages

### ISSUE THREAD

**Issue by robvanoostenrijk** [Luligu/zigbee2mqtt-automations#6]
Currently zigbee2mqtt-automations only trigger on Zigbee state changes.

I have some automations configured which I'd love to trigger via other means as well.
Would it be feasible to add logic to trigger automations on MQTT messages received?

**Comment by Luligu** [comment]
Hi,
you are right it triggers only for state changes and also for sun moon etc events.
The idea to trigger with mqtt is really interesting and not too difficult to achieve but I cannot install packages cause it runs inside z2m.
Next refactoring will try to check it!

**Comment by robvanoostenrijk** [comment]
If you are happy with the PR, no need to assign it yourself then.

**Comment by Luligu** [comment]
Merged.

Thanks.
